### ISSUE TITLE
Field description shouldnt be mandatory

### ISSUE THREAD

**Issue by patricechataigner** [oiime/sidr#3] opened 2015-11-29 14:33 UTC
Leads   Manual entry    

An error occur when we try to upload a document and if the field "description"  is left empty. it woul dbe good also in this section to have an option to delete the doc uploaded in case we loaded the wrong doc. also, in addition to the option to browse your computer for the document, it is possible to have a drag and drop box where we simply drag and drop the document? this would speed the process

**Comment by oiime** [comment] 2015-11-30 11:16
duplicate of #3

**Closed as completed by oiime** 2015-11-30 11:16 UTC
